baseurl: /jekyll_demo
name: "Silan's Blog"
description: "Learning"

url: "chensilan.me"

paginate: 10
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
safe: false

title:  Silan's Blog
tagline: Site Tagline
author: 
  name: Silan(Sally) Chen
  email:  silan0318@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  facebook: https://www.facebook.com/profile.php?id=100006754483664
  github: https://github.com/chenlanlan
  linkedin: https://www.linkedin.com/in/silanchen

production_url : http://chenlanlan.github.io/jekyll_demo

JB :
  version : 0.3.0

BASE_PATH : /blog
ASSET_PATH : False

 archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

comments :
    provider : disqus
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light

  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-50637568-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'  

 sharing :
    provider : false