# Site settings
title: Silan's Blog
email: silan0318@gmail.com
description: "Python,Java,HTML,CSS,Machine Leaning"
permalink: pretty
baseurl: ""
url: "//chensilan.me"
atom-baseurl: "chensilan.me"
author: "SilanChen"
img_url: http://chenlanlan.github.io/jekyll_demo/img
# Build settings
# permalink: date
pygments: true
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : taizilongxu

navigations:
  - title: About
    class: fa fa-list-ul
    href: /about/
  - title: Archive
    class: fa fa-tags
    href: /archive/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title: Tags
    class: fa fa-film
    href: /tags/
  - title: Contact
    class: fa fa-rss
    href: /contact/
