baseurl: /jekyll_demo
name: "Silan's Blog"
description: "Learning"

url: "chensilan.me"

paginate: 10

title:            Silan's Blog
description:      Write down something to record~
logo:             site-logo.png
disqus_shortname: shortname
search:           true
url:              http://localhost:4000

# Owner/author information
owner:
  name:           Silan(Sally) Chen
  avatar:         your-photo.jpg
  email:          silan0318@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  facebook: https://www.facebook.com/profile.php?id=100006754483664
  github: https://github.com/chenlanlan
  linkedin: https://www.linkedin.com/in/silanchen

# Links to include in top navigation
# For external links add external: true
links:
  - title: Facebook
    url: https://www.facebook.com/profile.php?id=100006754483664
  - title: Github
    url: /https://github.com/chenlanlan
  - title: Linkedin
    url: https://www.linkedin.com/in/silanchen
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty